### PR TITLE
Retrieve the JJB password from Jenkins credentials

### PR DESCRIPTION
**Pull request by paride**

### CODE REVIEW

**Comment by paride** [comment]
Marked WIP as it will require rebasing after https://github.com/canonical/server-jenkins-jobs/pull/156 lands.

**Comment by paride** [comment]
Not WIP anymore, ready for review / comment.

**Comment by paride** [comment]
This PR is tested working.

I explain the rationale for storing `jenkins_jobs.ini` in the repo in the commit message:

```
The change also allows to store jenkins_jobs.ini in the repository, as
it doesn't contain credentials anymore. This will allow to store
repository-specific settings in the file, e.g. jenkins-job-linter
settings.
```

**Review by blackboxsw — COMMENTED** [review]
Thanks for this and the context in the commit msg.

**Pull request merged**
