### PR TITLE
Allow recursive test/deploy operations on jobs

### PR DESCRIPTION
**Pull request by paride**

### CODE REVIEW

**Comment by paride** [comment]
See commit message for rationale.

The definitions are bug-by-bug compatible with the previous ones, the only differences in the resulting XMLs are:
```
--- A/git-ubuntu-ci	2020-11-20 14:59:24.469543382 +0100
+++ B/git-ubuntu-ci	2020-11-20 15:40:16.157862410 +0100
@@ -113,7 +113,7 @@
       <parameterDefinitions>
         <hudson.model.StringParameterDefinition>
           <name>candidate_revision</name>
-          <description>Hash revision of the branch to test (e.g. 'c6af5b9a1648c208c82b3a2704668391abadd8ab')</description>
+          <description>Revision of the branch to test. (e.g. 'c6af5b9a1648c208c82b3a2704668391abadd8ab')</description>
           <defaultValue/>
           <trim>false</trim>
         </hudson.model.StringParameterDefinition>
@@ -131,7 +131,7 @@
         </hudson.model.StringParameterDefinition>
         <hudson.model.StringParameterDefinition>
           <name>merge_proposal</name>
-          <description>URL of merge proposal to process to test (e.g. https://code.launchpad.net/~smoser/cloud-init/+git/cloud-init/+merge/325760)</description>
+          <description>Merge proposal to process to test. (e.g. https://code.launchpad.net/~raharper/curtin/+git/curtin/+merge/370800)</description>
           <defaultValue/>
           <trim>false</trim>
         </hudson.model.StringParameterDefinition>

--- A/simplestreams-ci	2020-11-20 14:59:27.969640507 +0100
+++ B/simplestreams-ci	2020-11-20 15:40:16.185862678 +0100
@@ -47,13 +47,13 @@
         </hudson.model.StringParameterDefinition>
         <hudson.model.StringParameterDefinition>
           <name>candidate_revision</name>
-          <description>Revision of the branch to test.</description>
+          <description>Revision of the branch to test. (e.g. 'c6af5b9a1648c208c82b3a2704668391abadd8ab')</description>
           <defaultValue/>
           <trim>false</trim>
         </hudson.model.StringParameterDefinition>
         <hudson.model.StringParameterDefinition>
           <name>merge_proposal</name>
-          <description>Merge proposal to process to test.</description>
+          <description>Merge proposal to process to test. (e.g. https://code.launchpad.net/~raharper/curtin/+git/curtin/+merge/370800)</description>
           <defaultValue/>
           <trim>false</trim>
         </hudson.model.StringParameterDefinition>
```

**Comment by paride** [comment]
Easy way to check the difference with `master`:
```
#!/bin/bash
set -e

rm -rf /tmp/{A,B}
mkdir /tmp/{A,B}

git checkout master

for dir in jenkins-jobs/*/; do
    jenkins-jobs test -o /tmp/A "$dir"
done

git checkout make-recursion-possible

jenkins-jobs test -o /tmp/B --recursive jenkins-jobs

diff -urN /tmp/{A,B}
```

**Comment by paride** [comment]
While doing these changes I spotted some issues with the jobs, mostly related to the fact that JJB defaults are overwritten in jobs, not extended (known limitation of JJB). For example a `timeout` wrapper set in `defaults` if lost is a job has its own `- wrappers:` section, and has to be added again.

This is why we ended with some stuck curtin jobs recently, as @mwhudson noticed. I didn't take care of those issue as part of this change, the diff is already painful enough to watch.

**Review by OddBloke — APPROVED** [review]
This all looks good, thanks Paride! I've confirmed locally that the changes in rendered output are minimal, as described.

**Comment by OddBloke** [comment]
> While doing these changes I spotted some issues with the jobs, mostly related to the fact that JJB defaults are overwritten in jobs, not extended (known limitation of JJB). For example a `timeout` wrapper set in `defaults` if lost is a job has its own `- wrappers:` section, and has to be added again.
> 
> This is why we ended with some stuck curtin jobs recently, as @mwhudson noticed. I didn't take care of those issue as part of this change, the diff is already painful enough to watch.

I wrote jenkins-job-linter (https://jenkins-job-linter.readthedocs.io/en/latest/; https://github.com/OddBloke/jenkins-job-linter) when I was on CPC, to handle linting the rendered jobs to catch these sorts of inconsistencies. If that sounds like something that might be useful for us, let me know and we can chat!

**Comment by paride** [comment]
@OddBloke heh, I have it already in a local `tox.ini` which I still have to commit :)

I saw you name around j-b-linter, but didn't know you wrote it!

**Pull request merged**
