### PR TITLE
oci unit: add squid

### PR DESCRIPTION
**Pull request by paride**

### CODE REVIEW

**Comment by paride** [comment]
1-liner to add the squid oci test to Jenkins. This assumes that the image will be published under both the `ubuntu` and `lts` namespaces.

**Comment by sergiodj** [comment]
+1 from me.  And your assumption is correct: the image will be published under `ubuntu` and `lts`.

**Review by sergiodj — APPROVED** [review]

**Comment by paride** [comment]
Let's hit Merge once the image is available to we don't get useless Jenkins failure emails :)

**Comment by paride** [comment]
This is ripe, landing it!

**Pull request merged**
