### PR TITLE
lma-integration: do not run tests with lxd-runner

### PR DESCRIPTION
**Pull request by paride**

### CODE REVIEW

**Comment by paride** [comment]
The Jenkins job failed because LXD was stuck on the machine where the job ran. I've got it unstuck, but still we can skip `lxd-runner` to make things simpler and hopefully more reliable.

**Comment by sergiodj** [comment]
LGTM, thanks!

**Comment by sergiodj** [comment]
Something I remembered now: the output of `./run-tests` is different now because of the containerization work I did.  I'm assuming that there is nothing else that needs to be adjusted because of this.  Am I correct?  :-)

**Comment by paride** [comment]
@sergiodj Jenkins cares about the exit code, and I don't think we're parting the output anywhere...

**Comment by sergiodj** [comment]
@paride OK, that's what I thought.  Cool!

**Pull request merged**
